### ISSUE TITLE
Follow Azure SDK for Python guidelines

### ISSUE THREAD

**Issue by vxfield** [microsoft/qdk-python#28]
We need to follow Azure SDK for Python [guidelines](https://azure.github.io/azure-sdk/python_introduction.html), including:
- [x] Use track2 generated client  (#54)
- [x] Support authentication with Azure Identity (#54)
- [x] Fix code styling (PEP8) issues (#56)
- [] Update the CI pipeline to enforce style guidelines (being addressed by #50)
- [x] Address all open conversations/suggestions from PR #25 (make sure to expand all the hidden conversations in that PR) 
- [x] Have unit tests to support running against live environment (using Azure ARM template for live test environment deployment)

**Comment by guenp** [comment]
As suggested during our team sync by @cgranade, I think as part of addressing the PEP8 issues we should update the pipeline to enforce style guidelines, we could use e.g. [flake8](https://flake8.pycqa.org/en/latest/) for that.

**Comment by vxfield** [comment]
Closing this as all tasks were done or are being tracked by another issue.
